/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersOnlineRouteImport } from './routes/users/online'
import { Route as UsersNewRouteImport } from './routes/users/new'
import { Route as UsersListRouteImport } from './routes/users/list'
import { Route as UsersLayoutRouteImport } from './routes/users/_layout'
import { Route as PackagesNewRouteImport } from './routes/packages/new'
import { Route as PackagesListRouteImport } from './routes/packages/list'
import { Route as PackagesLayoutRouteImport } from './routes/packages/_layout'
import { Route as NasNewRouteImport } from './routes/nas/new'
import { Route as NasListRouteImport } from './routes/nas/list'
import { Route as NasLayoutRouteImport } from './routes/nas/_layout'
import { Route as ManagersNewRouteImport } from './routes/managers/new'
import { Route as ManagersListRouteImport } from './routes/managers/list'
import { Route as ManagersLayoutRouteImport } from './routes/managers/_layout'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersOnlineRoute = UsersOnlineRouteImport.update({
  id: '/users/online',
  path: '/users/online',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersListRoute = UsersListRouteImport.update({
  id: '/users/list',
  path: '/users/list',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersLayoutRoute = UsersLayoutRouteImport.update({
  id: '/users/_layout',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesNewRoute = PackagesNewRouteImport.update({
  id: '/packages/new',
  path: '/packages/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesListRoute = PackagesListRouteImport.update({
  id: '/packages/list',
  path: '/packages/list',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesLayoutRoute = PackagesLayoutRouteImport.update({
  id: '/packages/_layout',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const NasNewRoute = NasNewRouteImport.update({
  id: '/nas/new',
  path: '/nas/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NasListRoute = NasListRouteImport.update({
  id: '/nas/list',
  path: '/nas/list',
  getParentRoute: () => rootRouteImport,
} as any)
const NasLayoutRoute = NasLayoutRouteImport.update({
  id: '/nas/_layout',
  path: '/nas',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagersNewRoute = ManagersNewRouteImport.update({
  id: '/managers/new',
  path: '/managers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagersListRoute = ManagersListRouteImport.update({
  id: '/managers/list',
  path: '/managers/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagersLayoutRoute = ManagersLayoutRouteImport.update({
  id: '/managers/_layout',
  path: '/managers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/managers': typeof ManagersLayoutRoute
  '/managers/list': typeof ManagersListRoute
  '/managers/new': typeof ManagersNewRoute
  '/nas': typeof NasLayoutRoute
  '/nas/list': typeof NasListRoute
  '/nas/new': typeof NasNewRoute
  '/packages': typeof PackagesLayoutRoute
  '/packages/list': typeof PackagesListRoute
  '/packages/new': typeof PackagesNewRoute
  '/users': typeof UsersLayoutRoute
  '/users/list': typeof UsersListRoute
  '/users/new': typeof UsersNewRoute
  '/users/online': typeof UsersOnlineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/managers': typeof ManagersLayoutRoute
  '/managers/list': typeof ManagersListRoute
  '/managers/new': typeof ManagersNewRoute
  '/nas': typeof NasLayoutRoute
  '/nas/list': typeof NasListRoute
  '/nas/new': typeof NasNewRoute
  '/packages': typeof PackagesLayoutRoute
  '/packages/list': typeof PackagesListRoute
  '/packages/new': typeof PackagesNewRoute
  '/users': typeof UsersLayoutRoute
  '/users/list': typeof UsersListRoute
  '/users/new': typeof UsersNewRoute
  '/users/online': typeof UsersOnlineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/managers/_layout': typeof ManagersLayoutRoute
  '/managers/list': typeof ManagersListRoute
  '/managers/new': typeof ManagersNewRoute
  '/nas/_layout': typeof NasLayoutRoute
  '/nas/list': typeof NasListRoute
  '/nas/new': typeof NasNewRoute
  '/packages/_layout': typeof PackagesLayoutRoute
  '/packages/list': typeof PackagesListRoute
  '/packages/new': typeof PackagesNewRoute
  '/users/_layout': typeof UsersLayoutRoute
  '/users/list': typeof UsersListRoute
  '/users/new': typeof UsersNewRoute
  '/users/online': typeof UsersOnlineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/managers'
    | '/managers/list'
    | '/managers/new'
    | '/nas'
    | '/nas/list'
    | '/nas/new'
    | '/packages'
    | '/packages/list'
    | '/packages/new'
    | '/users'
    | '/users/list'
    | '/users/new'
    | '/users/online'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/managers'
    | '/managers/list'
    | '/managers/new'
    | '/nas'
    | '/nas/list'
    | '/nas/new'
    | '/packages'
    | '/packages/list'
    | '/packages/new'
    | '/users'
    | '/users/list'
    | '/users/new'
    | '/users/online'
  id:
    | '__root__'
    | '/'
    | '/signup'
    | '/managers/_layout'
    | '/managers/list'
    | '/managers/new'
    | '/nas/_layout'
    | '/nas/list'
    | '/nas/new'
    | '/packages/_layout'
    | '/packages/list'
    | '/packages/new'
    | '/users/_layout'
    | '/users/list'
    | '/users/new'
    | '/users/online'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignupRoute: typeof SignupRoute
  ManagersLayoutRoute: typeof ManagersLayoutRoute
  ManagersListRoute: typeof ManagersListRoute
  ManagersNewRoute: typeof ManagersNewRoute
  NasLayoutRoute: typeof NasLayoutRoute
  NasListRoute: typeof NasListRoute
  NasNewRoute: typeof NasNewRoute
  PackagesLayoutRoute: typeof PackagesLayoutRoute
  PackagesListRoute: typeof PackagesListRoute
  PackagesNewRoute: typeof PackagesNewRoute
  UsersLayoutRoute: typeof UsersLayoutRoute
  UsersListRoute: typeof UsersListRoute
  UsersNewRoute: typeof UsersNewRoute
  UsersOnlineRoute: typeof UsersOnlineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/online': {
      id: '/users/online'
      path: '/users/online'
      fullPath: '/users/online'
      preLoaderRoute: typeof UsersOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/list': {
      id: '/users/list'
      path: '/users/list'
      fullPath: '/users/list'
      preLoaderRoute: typeof UsersListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/_layout': {
      id: '/users/_layout'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/new': {
      id: '/packages/new'
      path: '/packages/new'
      fullPath: '/packages/new'
      preLoaderRoute: typeof PackagesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/list': {
      id: '/packages/list'
      path: '/packages/list'
      fullPath: '/packages/list'
      preLoaderRoute: typeof PackagesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/_layout': {
      id: '/packages/_layout'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nas/new': {
      id: '/nas/new'
      path: '/nas/new'
      fullPath: '/nas/new'
      preLoaderRoute: typeof NasNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nas/list': {
      id: '/nas/list'
      path: '/nas/list'
      fullPath: '/nas/list'
      preLoaderRoute: typeof NasListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nas/_layout': {
      id: '/nas/_layout'
      path: '/nas'
      fullPath: '/nas'
      preLoaderRoute: typeof NasLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managers/new': {
      id: '/managers/new'
      path: '/managers/new'
      fullPath: '/managers/new'
      preLoaderRoute: typeof ManagersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managers/list': {
      id: '/managers/list'
      path: '/managers/list'
      fullPath: '/managers/list'
      preLoaderRoute: typeof ManagersListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managers/_layout': {
      id: '/managers/_layout'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof ManagersLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignupRoute: SignupRoute,
  ManagersLayoutRoute: ManagersLayoutRoute,
  ManagersListRoute: ManagersListRoute,
  ManagersNewRoute: ManagersNewRoute,
  NasLayoutRoute: NasLayoutRoute,
  NasListRoute: NasListRoute,
  NasNewRoute: NasNewRoute,
  PackagesLayoutRoute: PackagesLayoutRoute,
  PackagesListRoute: PackagesListRoute,
  PackagesNewRoute: PackagesNewRoute,
  UsersLayoutRoute: UsersLayoutRoute,
  UsersListRoute: UsersListRoute,
  UsersNewRoute: UsersNewRoute,
  UsersOnlineRoute: UsersOnlineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
